Fix Missing "Time left" in DB when queue is cleared
SamLab17/HelpHours pull request #59
Opened 2020-09-29 22:05 UTC by SamLab17

Fixes #49

2020-10-02 05:05 UTC, ClosingBracket requested changes

2020-10-02 05:05 UTC, ClosingBracket commented on helphours/routes_helper.py
> +    remove_helper(uid, was_helped=('finised' in request.form), instructor_id=g.user.id)
finished

2020-10-02 05:05 UTC, ClosingBracket commented on helphours/routes_helper.py
> +        log.error(f"DId not find entry for {uid} in the visits table.")
typo

2020-10-02 05:05 UTC, SamLab17 commented on helphours/routes_helper.py
> +        log.error(f"DId not find entry for {uid} in the visits table.")
bro get outta here with your outdated requests

2020-10-06 05:19 UTC, ClosingBracket approved these changes
Nice!

2020-10-06 18:43 UTC, ninaahmed approved these changes
Nice

2020-10-11 19:51 UTC, merged